"""empty message

Revision ID: 6abe93b61b30
Revises: bb8cb71d1efc
Create Date: 2019-10-09 19:31:55.358705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6abe93b61b30'
down_revision = 'bb8cb71d1efc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('device_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'data', type_='foreignkey')
    op.create_foreign_key(None, 'data', 'devices', ['device_id'], ['id'])
    op.drop_column('data', 'device')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('device', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'data', type_='foreignkey')
    op.create_foreign_key(None, 'data', 'devices', ['device'], ['id'])
    op.drop_column('data', 'device_id')
    # ### end Alembic commands ###
