"""empty message

Revision ID: b4de4f52f014
Revises: db597c1ba2e8
Create Date: 2019-10-22 15:30:40.509021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4de4f52f014'
down_revision = 'db597c1ba2e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('ip', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'ip')
    # ### end Alembic commands ###
