"""empty message

Revision ID: bb8cb71d1efc
Revises: 5e73ecd556f0
Create Date: 2019-10-09 19:25:42.464256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb8cb71d1efc'
down_revision = '5e73ecd556f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('crowdedness', sa.Integer(), nullable=True))
    op.add_column('locations', sa.Column('coordinate_x', sa.Float(), nullable=True))
    op.add_column('locations', sa.Column('coordinate_y', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'coordinate_y')
    op.drop_column('locations', 'coordinate_x')
    op.drop_column('data', 'crowdedness')
    # ### end Alembic commands ###
